spring:
  application:
    name: msfuncionarios
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./funcionarios-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /docs-funcionarios.html
  api-docs:
    path: /docs-funcionarios
  packagesToScan: bytestorm.msfuncionarios.web.controller

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka