spring:
  application:
    name: msfuncionarios
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./alunos-db
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
#  doc:
#    swagger-ui:
#      path: /docs-alunos.html
#    api-docs:
#      path: /docs-alunos
#    packagesToScan: com.bytestorm.alunos.web.controller

server:
  port: 8081
