version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  eureka:
    build:
      context: ./eurekaserver
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    ports:
      - "8761:8761"

  msfuncionarios:
    build:
      context: ./msfuncionarios
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - eureka

  ms-propostas:
    build:
      context: ./ms-propostas
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - eureka
      - msfuncionarios

  msresultados:
    build:
      context: ./msresultados
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - eureka

  ms-gateway:
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - eureka
      - msfuncionarios
      - ms-propostas
      - msresultados

networks:
  broker-kafka:
    driver: bridge