spring:
  application:
    name: ms-propostas
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  datasource:
    url: jdbc:h2:file:./propostas-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /docs-propostas.html
  api-docs:
    path: /docs-propostas
  packages-to-scan: com.bytestorm.ms_propostas.web