spring:
  application:
    name: ms-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka