spring:
  application:
    name: msresultados
  mvc:
    locale-resolver: fixed
    locale: pt_BR
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./resultados-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /docs-resultados.html
  api-docs:
    path: /docs-resultados
  packagesToScan: bytestorm.msresultados.web.controller

server:
  port: 8082